version: '3'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: orkg-templates-recommendation_elastic_container
    environment:
    - node.name=es01
    - discovery.type=single-node
    - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata01:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

volumes:
  esdata01:
    driver: local